name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1043622436944/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@smartsheet-automation-demo.iam.gserviceaccount.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/smartsheet-automation-demo/smartsheet-automation-repo/smartsheet-automation:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/smartsheet-automation-demo/smartsheet-automation-repo/smartsheet-automation:${{ github.sha }}